[menu]
background                = "#49453F"
background-alpha          = 0.66
text                      = "#F2EEE5"
border                    = "hyprland.active-border-foreground"
border-alpha              = 0.65
scrim                     = "#34312D"
scrim-alpha               = 0.18
selected-background       = "#F2EEE5"
selected-background-alpha = 0.08
selected-text             = "#E4AC88"
selected-border           = "hyprland.active-border-foreground"
selected-border-alpha     = 0.25
